@{
    # ============================================================
    # Organization Identity
    #   Use the same OrganizationName configured in DeviceLifecycle.
    #   Installation paths and Windows object names are derived from
    #   this value unless explicitly overridden below.
    # ============================================================
    OrganizationName = 'orgname'

    # DeviceLifecycle data source. Leave blank to derive:
    # C:\ProgramData\{OrganizationName}\DeviceLifecycle
    DataRoot = ''

    # API installation. Leave blank to derive:
    # C:\Program Files\{OrganizationName}\DeviceLifecycle-API
    InstallRoot = ''

    # Runtime configuration and API logs. Leave blank to derive:
    # C:\ProgramData\{OrganizationName}\DeviceLifecycleApi
    ConfigRoot = ''

    # Windows integration names. Leave blank to derive:
    # {OrganizationName} - Device Lifecycle API
    TaskName = ''
    FirewallRuleName = ''

    # Network listener.
    ListenAddress = '0.0.0.0'
    Port = 8088

    # Restrict the inbound firewall rule to approved consumers.
    # Examples: @('192.168.1.20') or @('192.168.1.20', '192.168.1.21')
    # An empty array creates no inbound firewall rule.
    RemoteAddress = @()

    # Source files generated by the DeviceLifecycle repository.
    ReportRelativePath = 'Reports\DeviceLifecycle-Latest.csv'
    LogDirectoryRelativePath = 'Logs'

    # Maximum value accepted by GET /api/v1/log?lines=N.
    MaxLogLines = 5000

    # Set to $true to also require X-API-Key on /api/v1/health.
    HealthRequiresAuthentication = $false

    # Optional explicit Python executable. Leave blank to auto-detect
    # python.exe or py.exe. Python 3.10 or newer is required.
    PythonExecutable = ''
}
